// Angular framework adapter for `implement_demo_for_framework`.
// Uses Angular 18+ standalone components, signals for state, and
// inline templates to keep generated files self-contained.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

export const FRAMEWORK = 'angular';

export function generateStores(projectDir, spec) {
  const files = [];
  for (const entity of spec.entities) {
    const file = join(projectDir, 'src', 'app', 'stores', `${entity.name.toLowerCase()}.store.ts`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, angularStore(entity));
    files.push(file);
  }
  return files;
}

function angularStore(entity) {
  const idField = entity.fields.find((f) => f.name.toLowerCase() === 'id') || entity.fields[0];
  const idName = idField?.name ?? 'id';
  const lower = entity.name.toLowerCase();
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
import { Injectable, signal } from '@angular/core';
import type { ${entity.name} } from '../types';
import { seed${entity.name} } from '../../data/seed';

const STORAGE_KEY = 'implement-demo/${lower}/v1';

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function load(): ${entity.name}[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw) as ${entity.name}[];
  } catch {
    // ignore
  }
  return clone(seed${entity.name});
}

function persist(items: ${entity.name}[]) {
  try { localStorage.setItem(STORAGE_KEY, JSON.stringify(items)); } catch { /* noop */ }
}

@Injectable({ providedIn: 'root' })
export class ${entity.name}Store {
  readonly items = signal<${entity.name}[]>(load());

  add(item: ${entity.name}) {
    const next = [...this.items(), item];
    this.items.set(next);
    persist(next);
  }

  update(id: string, patch: Partial<${entity.name}>) {
    const current = this.items();
    const ix = current.findIndex((x) => String((x as Record<string, unknown>).${idName}) === id);
    if (ix === -1) return false;
    const next = [...current];
    next[ix] = { ...next[ix], ...patch };
    this.items.set(next);
    persist(next);
    return true;
  }

  remove(id: string) {
    const next = this.items().filter((x) => String((x as Record<string, unknown>).${idName}) !== id);
    this.items.set(next);
    persist(next);
  }

  reset() {
    const fresh = clone(seed${entity.name});
    this.items.set(fresh);
    persist(fresh);
  }

  get(id: string) {
    return this.items().find((x) => String((x as Record<string, unknown>).${idName}) === id);
  }
}
`;
}

export function generatePages(projectDir, spec) {
  const files = [];
  for (const page of spec.pages) {
    const code = renderPage(page, spec);
    const file = join(projectDir, 'src', 'app', 'pages', `${pageFileName(page)}.component.ts`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, code);
    files.push(file);
  }
  return files;
}

function pageComponentName(page) {
  const safe = page.name.replace(/[^a-zA-Z0-9]/g, '');
  return safe.charAt(0).toUpperCase() + safe.slice(1) + 'PageComponent';
}

function pageFileName(page) {
  return page.name.replace(/[^a-zA-Z0-9]/g, '').toLowerCase() + '-page';
}

function pageSelector(page) {
  return 'app-' + page.name.replace(/[^a-zA-Z0-9]/g, '').toLowerCase() + '-page';
}

function renderPage(page, spec) {
  if (page.kind === 'list-detail') return renderListDetail(page, spec);
  if (page.kind === 'dashboard') return renderDashboard(page, spec);
  if (page.kind === 'form-wizard') return renderFormWizard(page, spec);
  return `import { Component } from '@angular/core';\n@Component({ standalone: true, template: 'Unknown kind: ${page.kind}' }) export class ${pageComponentName(page)} {}`;
}

function renderListDetail(page, spec) {
  const entity = spec.entities.find((e) => e.name === page.primaryEntity);
  if (!entity) {
    return `import { Component } from '@angular/core';\n@Component({ standalone: true, template: 'Entity ${page.primaryEntity} not found' }) export class ${pageComponentName(page)} {}`;
  }
  const lower = entity.name.toLowerCase();
  const colHeaders = entity.fields
    .filter((f) => f.type !== 'object' && f.type !== 'array')
    .slice(0, 6)
    .map((f) => `            <th>${humanLabel(f.name)}</th>`)
    .join('\n');
  const tdFields = entity.fields
    .filter((f) => f.type !== 'object' && f.type !== 'array')
    .slice(0, 6)
    .map((f) => `              <td>{{ asRecord(item).${f.name} ?? '—' }}</td>`)
    .join('\n');
  const filters = page.filters || entity.fields.filter((f) => f.type === 'string' || f.type === 'enum').slice(0, 2).map((f) => f.name);
  const filterInputs = filters
    .map(
      (name) => `          <label class="field">
            <span>${humanLabel(name)}</span>
            <input [(ngModel)]="filters.${name}" placeholder="Buscar" />
          </label>`
    )
    .join('\n');
  const filterChecks = filters
    .map(
      (n) =>
        `      if (this.filters.${n} && !String(asRecord(it).${n} ?? '').toLowerCase().includes(this.filters.${n}.toLowerCase())) return false;`
    )
    .join('\n');
  const actions = (page.actions || [])
    .map(
      (a) =>
        `          <button (click)="onAction('${a}')" [disabled]="!selected">${humanLabel(a)}</button>`
    )
    .join('\n');
  const filtersInit = filters.map((n) => `    ${n}: '',`).join('\n');
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { ${entity.name}Store } from '../stores/${lower}.store';
import type { ${entity.name} } from '../types';

function asRecord(it: unknown): Record<string, unknown> {
  return it as Record<string, unknown>;
}

@Component({
  selector: '${pageSelector(page)}',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: \`
    <section class="page">
      <header><h1>${page.name}</h1></header>
      <div class="filters">
${filterInputs}
      </div>
      <div class="actions">
${actions || '          <button disabled>Sin acciones definidas</button>'}
      </div>
      <table>
        <thead><tr>
${colHeaders}
        </tr></thead>
        <tbody>
          @for (item of rows(); track $index) {
            <tr (click)="selected = item">
${tdFields}
            </tr>
          }
        </tbody>
      </table>
      @if (selected) {
        <aside class="detail">
          <header>
            <strong>Detalle</strong>
            <button (click)="selected = null">Cerrar</button>
          </header>
          <pre>{{ selected | json }}</pre>
        </aside>
      }
    </section>
  \`,
})
export class ${pageComponentName(page)} {
  private store = inject(${entity.name}Store);
  filters: Record<string, string> = {
${filtersInit}
  };
  selected: ${entity.name} | null = null;

  rows = computed(() =>
    this.store.items().filter((it) => {
${filterChecks}
      return true;
    })
  );

  asRecord = asRecord;

  onAction(action: string) {
    if (!this.selected) return;
    // eslint-disable-next-line no-console
    console.info('action', action, 'on', this.selected);
  }
}
`;
}

function renderDashboard(page, spec) {
  const entityNames = (spec.entities || []).slice(0, 3).map((e) => e.name);
  const imports = entityNames
    .map((n) => `import { ${n}Store } from '../stores/${n.toLowerCase()}.store';`)
    .join('\n');
  const injections = entityNames
    .map((n) => `  private ${n.toLowerCase()}Store = inject(${n}Store);`)
    .join('\n');
  const cards = entityNames
    .map(
      (n) =>
        `        <div class="kpi-card"><div class="kpi-value">{{ ${n.toLowerCase()}Store.items().length }}</div><div class="kpi-label">${humanLabel(n)}</div></div>`
    )
    .join('\n');
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
${imports}

@Component({
  selector: '${pageSelector(page)}',
  standalone: true,
  imports: [CommonModule],
  template: \`
    <section class="page">
      <header><h1>${page.name}</h1></header>
      <div class="kpi-grid">
${cards.replace(/\{\{ /g, '{{ this.')}
      </div>
    </section>
  \`,
})
export class ${pageComponentName(page)} {
${injections}
}
`;
}

function renderFormWizard(page, spec) {
  const entity = spec.entities.find((e) => e.name === page.primaryEntity) || spec.entities[0];
  if (!entity) {
    return `import { Component } from '@angular/core';\n@Component({ standalone: true, template: 'No entity' }) export class ${pageComponentName(page)} {}`;
  }
  const lower = entity.name.toLowerCase();
  const inputs = entity.fields
    .filter((f) => f.type === 'string' || f.type === 'number' || f.type === 'enum')
    .map((f) => {
      if (f.type === 'enum') {
        const opts = (f.options || [])
          .map((o) => `            <option value="${o}">${o}</option>`)
          .join('\n');
        return `        <label class="field">
          <span>${humanLabel(f.name)}</span>
          <select [(ngModel)]="form.${f.name}" name="${f.name}">
${opts}
          </select>
        </label>`;
      }
      const inputType = f.type === 'number' ? 'number' : 'text';
      return `        <label class="field">
          <span>${humanLabel(f.name)}</span>
          <input type="${inputType}" [(ngModel)]="form.${f.name}" name="${f.name}" />
        </label>`;
    })
    .join('\n');
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
import { Component, inject } from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { ${entity.name}Store } from '../stores/${lower}.store';
import type { ${entity.name} } from '../types';

@Component({
  selector: '${pageSelector(page)}',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: \`
    <section class="page">
      <header><h1>${page.name}</h1></header>
      <form #f="ngForm" (ngSubmit)="submit(f)">
${inputs}
        <button type="submit">Crear</button>
      </form>
    </section>
  \`,
})
export class ${pageComponentName(page)} {
  private store = inject(${entity.name}Store);
  form: Partial<${entity.name}> = {};

  submit(_form: NgForm) {
    this.store.add(this.form as ${entity.name});
    this.form = {};
  }
}
`;
}

function humanLabel(name) {
  return String(name).replace(/[-_]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export function generateRouter(projectDir, spec) {
  const imports = spec.pages.map((p) => {
    const cls = pageComponentName(p);
    return `import { ${cls} } from './pages/${pageFileName(p)}.component';`;
  });
  const routes = spec.pages
    .map((p) => {
      const cls = pageComponentName(p);
      const path = p.path.replace(/^\//, '');
      return `  { path: '${path}', component: ${cls} },`;
    })
    .join('\n');
  const firstPath = spec.pages[0]?.path?.replace(/^\//, '') ?? '';
  const code = `// Auto-generated by bonita-page implement-demo. Edit freely.
import { Routes } from '@angular/router';
${imports.join('\n')}

export const routes: Routes = [
  { path: '', redirectTo: '${firstPath}', pathMatch: 'full' },
${routes}
  { path: '**', redirectTo: '${firstPath}' },
];
`;
  const file = join(projectDir, 'src', 'app', 'app.routes.ts');
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, code);
  return [file];
}
