// Qwik framework adapter for `implement_demo_for_framework`.
// SPA-only mode (no Qwik City). Uses module-level signals as stores
// (the toolkit's documented pattern — see skills/bonita-qwik-app/) and
// a manual hash-based router via a `route` signal in root.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

export const FRAMEWORK = 'qwik';

export function generateStores(projectDir, spec) {
  const files = [];
  for (const entity of spec.entities) {
    const file = join(projectDir, 'src', 'stores', `${entity.name.toLowerCase()}Store.ts`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, qwikStore(entity));
    files.push(file);
  }
  return files;
}

function qwikStore(entity) {
  const idField = entity.fields.find((f) => f.name.toLowerCase() === 'id') || entity.fields[0];
  const idName = idField?.name ?? 'id';
  const lower = entity.name.toLowerCase();
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
// Qwik in SPA mode — module-level state with localStorage hydration.
// Components observe via a useSignal seeded from get().
import type { ${entity.name} } from '@/types';
import { seed${entity.name} } from '@/data/seed';

const STORAGE_KEY = 'implement-demo/${lower}/v1';

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

let _items: ${entity.name}[] = (() => {
  try {
    const raw = typeof localStorage !== 'undefined' ? localStorage.getItem(STORAGE_KEY) : null;
    if (raw) return JSON.parse(raw) as ${entity.name}[];
  } catch {
    // ignore
  }
  return clone(seed${entity.name});
})();

function persist() {
  try { localStorage.setItem(STORAGE_KEY, JSON.stringify(_items)); } catch { /* noop */ }
}

export const ${lower}Store = {
  get(): ${entity.name}[] { return _items; },
  add(item: ${entity.name}) {
    _items = [..._items, item];
    persist();
  },
  update(id: string, patch: Partial<${entity.name}>) {
    const ix = _items.findIndex((x) => String((x as Record<string, unknown>).${idName}) === id);
    if (ix === -1) return false;
    _items = _items.map((x, i) => (i === ix ? { ...x, ...patch } : x));
    persist();
    return true;
  },
  remove(id: string) {
    _items = _items.filter((x) => String((x as Record<string, unknown>).${idName}) !== id);
    persist();
  },
  reset() {
    _items = clone(seed${entity.name});
    persist();
  },
};
`;
}

export function generatePages(projectDir, spec) {
  const files = [];
  for (const page of spec.pages) {
    const code = renderPage(page, spec);
    const file = join(projectDir, 'src', 'pages', `${pageComponentName(page)}.tsx`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, code);
    files.push(file);
  }
  return files;
}

function pageComponentName(page) {
  const safe = page.name.replace(/[^a-zA-Z0-9]/g, '');
  return safe.charAt(0).toUpperCase() + safe.slice(1) + 'Page';
}

function renderPage(page, spec) {
  if (page.kind === 'list-detail') return renderListDetail(page, spec);
  if (page.kind === 'dashboard') return renderDashboard(page, spec);
  if (page.kind === 'form-wizard') return renderFormWizard(page, spec);
  return `import { component$ } from '@builder.io/qwik';\nexport default component$(() => <div>Unknown kind: ${page.kind}</div>);`;
}

function renderListDetail(page, spec) {
  const entity = spec.entities.find((e) => e.name === page.primaryEntity);
  if (!entity) {
    return `import { component$ } from '@builder.io/qwik';\nexport default component$(() => <div>Entity ${page.primaryEntity} not found</div>);`;
  }
  const lower = entity.name.toLowerCase();
  const cols = entity.fields
    .filter((f) => f.type !== 'object' && f.type !== 'array')
    .slice(0, 6)
    .map((f) => `          <th>${humanLabel(f.name)}</th>`)
    .join('\n');
  const tdFields = entity.fields
    .filter((f) => f.type !== 'object' && f.type !== 'array')
    .slice(0, 6)
    .map((f) => `              <td>{String((item as Record<string, unknown>).${f.name} ?? '—')}</td>`)
    .join('\n');
  const filters = page.filters || entity.fields.filter((f) => f.type === 'string' || f.type === 'enum').slice(0, 2).map((f) => f.name);
  const filterControls = filters
    .map(
      (name) => `        <label class="field">
          <span>${humanLabel(name)}</span>
          <input
            value={filters.value.${name} ?? ''}
            onInput$={(e) => (filters.value = { ...filters.value, ${name}: (e.target as HTMLInputElement).value })}
            placeholder="Buscar"
          />
        </label>`
    )
    .join('\n');
  const filterChecks = filters
    .map(
      (n) =>
        `        if (filters.value.${n} && !String((it as Record<string, unknown>).${n} ?? '').toLowerCase().includes(filters.value.${n}.toLowerCase())) return false;`
    )
    .join('\n');
  const actions = (page.actions || [])
    .map(
      (a) =>
        `        <button onClick$={() => onAction('${a}')} disabled={!selected.value}>${humanLabel(a)}</button>`
    )
    .join('\n');
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
import { component$, useSignal, useComputed$ } from '@builder.io/qwik';
import { ${lower}Store } from '@/stores/${lower}Store';
import type { ${entity.name} } from '@/types';

export default component$(() => {
  const items = useSignal<${entity.name}[]>(${lower}Store.get());
  const filters = useSignal<Record<string, string>>({});
  const selected = useSignal<${entity.name} | null>(null);

  const rows = useComputed$(() =>
    items.value.filter((it) => {
${filterChecks}
      return true;
    })
  );

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  function onAction(action: string) {
    if (!selected.value) return;
    // eslint-disable-next-line no-console
    console.info('action', action, 'on', selected.value);
  }

  return (
    <section class="page">
      <header><h1>${page.name}</h1></header>
      <div class="filters">
${filterControls}
      </div>
      <div class="actions">
${actions || '        <button disabled>Sin acciones definidas</button>'}
      </div>
      <table>
        <thead><tr>
${cols}
        </tr></thead>
        <tbody>
          {rows.value.map((item, idx) => (
            <tr key={idx} onClick$={() => (selected.value = item)}>
${tdFields}
            </tr>
          ))}
        </tbody>
      </table>
      {selected.value && (
        <aside class="detail">
          <header>
            <strong>Detalle</strong>
            <button onClick$={() => (selected.value = null)}>Cerrar</button>
          </header>
          <pre>{JSON.stringify(selected.value, null, 2)}</pre>
        </aside>
      )}
    </section>
  );
});
`;
}

function renderDashboard(page, spec) {
  const entityNames = (spec.entities || []).slice(0, 3).map((e) => e.name);
  const imports = entityNames
    .map((n) => `import { ${n.toLowerCase()}Store } from '@/stores/${n.toLowerCase()}Store';`)
    .join('\n');
  const cards = entityNames
    .map(
      (n) =>
        `        <div class="kpi-card"><div class="kpi-value">{${n.toLowerCase()}Store.get().length}</div><div class="kpi-label">${humanLabel(n)}</div></div>`
    )
    .join('\n');
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
import { component$ } from '@builder.io/qwik';
${imports}

export default component$(() => {
  return (
    <section class="page">
      <header><h1>${page.name}</h1></header>
      <div class="kpi-grid">
${cards}
      </div>
    </section>
  );
});
`;
}

function renderFormWizard(page, spec) {
  const entity = spec.entities.find((e) => e.name === page.primaryEntity) || spec.entities[0];
  if (!entity) {
    return `import { component$ } from '@builder.io/qwik';\nexport default component$(() => <div>No entity</div>);`;
  }
  const lower = entity.name.toLowerCase();
  const inputs = entity.fields
    .filter((f) => f.type === 'string' || f.type === 'number' || f.type === 'enum')
    .map((f) => {
      if (f.type === 'enum') {
        const opts = (f.options || []).map((o) => `          <option value="${o}">${o}</option>`).join('\n');
        return `      <label class="field">
        <span>${humanLabel(f.name)}</span>
        <select onChange$={(e) => (form.value = { ...form.value, ${f.name}: (e.target as HTMLSelectElement).value })}>
${opts}
        </select>
      </label>`;
      }
      const inputType = f.type === 'number' ? 'number' : 'text';
      const cast = inputType === 'number' ? 'Number((e.target as HTMLInputElement).value)' : '(e.target as HTMLInputElement).value';
      return `      <label class="field">
        <span>${humanLabel(f.name)}</span>
        <input type="${inputType}" onInput$={(e) => (form.value = { ...form.value, ${f.name}: ${cast} })} />
      </label>`;
    })
    .join('\n');
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
import { component$, useSignal, $ } from '@builder.io/qwik';
import { ${lower}Store } from '@/stores/${lower}Store';
import type { ${entity.name} } from '@/types';

export default component$(() => {
  const form = useSignal<Partial<${entity.name}>>({});

  const submit = $(() => {
    ${lower}Store.add(form.value as ${entity.name});
    form.value = {};
  });

  return (
    <section class="page">
      <header><h1>${page.name}</h1></header>
      <form preventdefault:submit onSubmit$={submit}>
${inputs}
        <button type="submit">Crear</button>
      </form>
    </section>
  );
});
`;
}

function humanLabel(name) {
  return String(name).replace(/[-_]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export function generateRouter(projectDir, spec) {
  const imports = spec.pages.map((p) => {
    const name = pageComponentName(p);
    return `import ${name} from './pages/${name}';`;
  });
  const cases = spec.pages
    .map((p) => {
      const name = pageComponentName(p);
      return `        case '${p.path}': return <${name} />;`;
    })
    .join('\n');
  const firstPath = spec.pages[0]?.path ?? '/';
  const code = `// Auto-generated by bonita-page implement-demo. Edit freely.
// Qwik SPA-only: manual hash router. Listen to hashchange and resolve
// the matching page component. Qwik City is incompatible with custom pages.
import { component$, useSignal, useVisibleTask$ } from '@builder.io/qwik';
${imports.join('\n')}

function currentPath(): string {
  if (typeof window === 'undefined') return '${firstPath}';
  return window.location.hash.replace(/^#/, '') || '${firstPath}';
}

export default component$(() => {
  const path = useSignal<string>(currentPath());

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ cleanup }) => {
    const onHash = () => { path.value = currentPath(); };
    if (!window.location.hash) window.location.hash = '${firstPath}';
    window.addEventListener('hashchange', onHash);
    cleanup(() => window.removeEventListener('hashchange', onHash));
  });

  return (() => {
    switch (path.value) {
${cases}
      default: return <${pageComponentName(spec.pages[0])} />;
    }
  })();
});
`;
  const file = join(projectDir, 'src', 'root.tsx');
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, code);
  return [file];
}
