// React framework adapter for `implement_demo_for_framework`.
// Uses Zustand (the toolkit's chosen state library for React) and
// react-router DOM v6 with createHashRouter.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

export const FRAMEWORK = 'react';

export function generateStores(projectDir, spec) {
  const files = [];
  for (const entity of spec.entities) {
    const file = join(projectDir, 'src', 'stores', `${entity.name.toLowerCase()}Store.ts`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, reactStore(entity));
    files.push(file);
  }
  return files;
}

function reactStore(entity) {
  const idField = entity.fields.find((f) => f.name.toLowerCase() === 'id') || entity.fields[0];
  const idName = idField?.name ?? 'id';
  const lower = entity.name.toLowerCase();
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
import { create } from 'zustand';
import type { ${entity.name} } from '@/types';
import { seed${entity.name} } from '@/data/seed';

const STORAGE_KEY = 'implement-demo/${lower}/v1';

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function load(): ${entity.name}[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw) as ${entity.name}[];
  } catch {
    // ignore
  }
  return clone(seed${entity.name});
}

function persist(items: ${entity.name}[]) {
  try { localStorage.setItem(STORAGE_KEY, JSON.stringify(items)); } catch { /* noop */ }
}

interface ${entity.name}State {
  items: ${entity.name}[];
  add: (item: ${entity.name}) => void;
  update: (id: string, patch: Partial<${entity.name}>) => boolean;
  remove: (id: string) => void;
  reset: () => void;
  get: (id: string) => ${entity.name} | undefined;
}

export const use${entity.name}Store = create<${entity.name}State>((set, getState) => ({
  items: load(),
  add: (item) =>
    set((s) => {
      const next = [...s.items, item];
      persist(next);
      return { items: next };
    }),
  update: (id, patch) => {
    const s = getState();
    const ix = s.items.findIndex((x) => String((x as Record<string, unknown>).${idName}) === id);
    if (ix === -1) return false;
    const next = [...s.items];
    next[ix] = { ...next[ix], ...patch };
    persist(next);
    set({ items: next });
    return true;
  },
  remove: (id) =>
    set((s) => {
      const next = s.items.filter((x) => String((x as Record<string, unknown>).${idName}) !== id);
      persist(next);
      return { items: next };
    }),
  reset: () => {
    const fresh = clone(seed${entity.name});
    persist(fresh);
    set({ items: fresh });
  },
  get: (id) => getState().items.find((x) => String((x as Record<string, unknown>).${idName}) === id),
}));
`;
}

export function generatePages(projectDir, spec) {
  const files = [];
  for (const page of spec.pages) {
    const code = renderPage(page, spec);
    const file = join(projectDir, 'src', 'pages', `${pageComponentName(page)}.tsx`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, code);
    files.push(file);
  }
  return files;
}

function pageComponentName(page) {
  const safe = page.name.replace(/[^a-zA-Z0-9]/g, '');
  return safe.charAt(0).toUpperCase() + safe.slice(1) + 'Page';
}

function renderPage(page, spec) {
  if (page.kind === 'list-detail') return renderListDetail(page, spec);
  if (page.kind === 'dashboard') return renderDashboard(page, spec);
  if (page.kind === 'form-wizard') return renderFormWizard(page, spec);
  return `export default function Page() { return <div>Unknown page kind: ${page.kind}</div>; }`;
}

function renderListDetail(page, spec) {
  const entity = spec.entities.find((e) => e.name === page.primaryEntity);
  if (!entity) {
    return `export default function ${pageComponentName(page)}() { return <div>Entity ${page.primaryEntity} not found in spec.</div>; }`;
  }
  const cols = entity.fields
    .filter((f) => f.type !== 'object' && f.type !== 'array')
    .slice(0, 6)
    .map((f) => `        <th>${humanLabel(f.name)}</th>`)
    .join('\n');
  const tdFields = entity.fields
    .filter((f) => f.type !== 'object' && f.type !== 'array')
    .slice(0, 6)
    .map((f) => `            <td>{String((item as Record<string, unknown>).${f.name} ?? '—')}</td>`)
    .join('\n');
  const filters = (page.filters || entity.fields.filter((f) => f.type === 'string' || f.type === 'enum').slice(0, 2).map((f) => f.name));
  const filterInputs = filters
    .map(
      (name) => `        <label className="field">
          <span>${humanLabel(name)}</span>
          <input
            value={filters.${name} ?? ''}
            onChange={(e) => setFilters((f) => ({ ...f, ${name}: e.target.value }))}
            placeholder="Buscar"
          />
        </label>`
    )
    .join('\n');
  const actions = (page.actions || []).map(
    (a) => `        <button onClick={() => onAction('${a}')} disabled={!selected}>${humanLabel(a)}</button>`
  ).join('\n');
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
import { useMemo, useState } from 'react';
import { use${entity.name}Store } from '@/stores/${entity.name.toLowerCase()}Store';
import type { ${entity.name} } from '@/types';

export default function ${pageComponentName(page)}() {
  const items = use${entity.name}Store((s) => s.items);
  const [filters, setFilters] = useState<Record<string, string>>({});
  const [selected, setSelected] = useState<${entity.name} | null>(null);

  const rows = useMemo(
    () =>
      items.filter((it) => {
${filters
  .map(
    (n) =>
      `        if (filters.${n} && !String((it as Record<string, unknown>).${n} ?? '').toLowerCase().includes(filters.${n}.toLowerCase())) return false;`
  )
  .join('\n')}
        return true;
      }),
    [items, filters]
  );

  function onAction(action: string) {
    if (!selected) return;
    // eslint-disable-next-line no-console
    console.info('action', action, 'on', selected);
  }

  return (
    <section className="page">
      <header>
        <h1>${page.name}</h1>
      </header>
      <div className="filters">
${filterInputs}
      </div>
      <div className="actions">
${actions || '        <button disabled>Sin acciones definidas</button>'}
      </div>
      <table>
        <thead><tr>
${cols}
        </tr></thead>
        <tbody>
          {rows.map((item, idx) => (
            <tr key={idx} onClick={() => setSelected(item)}>
${tdFields}
            </tr>
          ))}
        </tbody>
      </table>
      {selected && (
        <aside className="detail">
          <header>
            <strong>Detalle</strong>
            <button onClick={() => setSelected(null)}>Cerrar</button>
          </header>
          <pre>{JSON.stringify(selected, null, 2)}</pre>
        </aside>
      )}
    </section>
  );
}
`;
}

function renderDashboard(page, spec) {
  const entityNames = (spec.entities || []).slice(0, 3).map((e) => e.name);
  const imports = entityNames
    .map((n) => `import { use${n}Store } from '@/stores/${n.toLowerCase()}Store';`)
    .join('\n');
  const cards = entityNames
    .map(
      (n) =>
        `        <div className="kpi-card"><div className="kpi-value">{${n.toLowerCase()}Count}</div><div className="kpi-label">${humanLabel(n)}</div></div>`
    )
    .join('\n');
  const stateBindings = entityNames
    .map((n) => `  const ${n.toLowerCase()}Count = use${n}Store((s) => s.items.length);`)
    .join('\n');
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
${imports}

export default function ${pageComponentName(page)}() {
${stateBindings}
  return (
    <section className="page">
      <header><h1>${page.name}</h1></header>
      <div className="kpi-grid">
${cards}
      </div>
    </section>
  );
}
`;
}

function renderFormWizard(page, spec) {
  const entity = spec.entities.find((e) => e.name === page.primaryEntity) || spec.entities[0];
  if (!entity) {
    return `export default function ${pageComponentName(page)}() { return <div>No entity</div>; }`;
  }
  const inputs = entity.fields
    .filter((f) => f.type === 'string' || f.type === 'number' || f.type === 'enum')
    .map((f) => {
      if (f.type === 'enum') {
        const opts = (f.options || []).map((o) => `          <option value="${o}">${o}</option>`).join('\n');
        return `      <label className="field">
        <span>${humanLabel(f.name)}</span>
        <select value={String(form.${f.name} ?? '')} onChange={(e) => setForm((s) => ({ ...s, ${f.name}: e.target.value }))}>
${opts}
        </select>
      </label>`;
      }
      const inputType = f.type === 'number' ? 'number' : 'text';
      return `      <label className="field">
        <span>${humanLabel(f.name)}</span>
        <input
          type="${inputType}"
          value={String(form.${f.name} ?? '')}
          onChange={(e) => setForm((s) => ({ ...s, ${f.name}: ${inputType === 'number' ? 'Number(e.target.value)' : 'e.target.value'} }))}
        />
      </label>`;
    })
    .join('\n');
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
import { useState } from 'react';
import { use${entity.name}Store } from '@/stores/${entity.name.toLowerCase()}Store';
import type { ${entity.name} } from '@/types';

export default function ${pageComponentName(page)}() {
  const add = use${entity.name}Store((s) => s.add);
  const [form, setForm] = useState<Partial<${entity.name}>>({});

  function submit(e: React.FormEvent) {
    e.preventDefault();
    add(form as ${entity.name});
    setForm({});
  }

  return (
    <section className="page">
      <header><h1>${page.name}</h1></header>
      <form onSubmit={submit}>
${inputs}
        <button type="submit">Crear</button>
      </form>
    </section>
  );
}
`;
}

function humanLabel(name) {
  return String(name).replace(/[-_]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export function generateRouter(projectDir, spec) {
  const imports = spec.pages.map((p) => {
    const name = pageComponentName(p);
    return `import ${name} from '@/pages/${name}';`;
  });
  const routes = spec.pages.map((p) => {
    const name = pageComponentName(p);
    const path = p.path.replace(/^\//, '');
    return `      { path: '${path}', element: <${name} /> },`;
  });
  const firstPath = spec.pages[0]?.path?.replace(/^\//, '') ?? '';
  const code = `// Auto-generated by bonita-page implement-demo. Edit freely.
import { createHashRouter, Navigate, Outlet } from 'react-router-dom';
${imports.join('\n')}

export const router = createHashRouter([
  {
    element: <Outlet />,
    children: [
      { index: true, element: <Navigate to="${firstPath}" replace /> },
${routes.join('\n')}
    ],
  },
  { path: '*', element: <Navigate to="/" replace /> },
]);
`;
  const file = join(projectDir, 'src', 'router.tsx');
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, code);
  return [file];
}
