// SolidJS framework adapter for `implement_demo_for_framework`.
// Uses createStore for state and @solidjs/router's HashRouter.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

export const FRAMEWORK = 'solid';

export function generateStores(projectDir, spec) {
  const files = [];
  for (const entity of spec.entities) {
    const file = join(projectDir, 'src', 'stores', `${entity.name.toLowerCase()}Store.ts`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, solidStore(entity));
    files.push(file);
  }
  return files;
}

function solidStore(entity) {
  const idField = entity.fields.find((f) => f.name.toLowerCase() === 'id') || entity.fields[0];
  const idName = idField?.name ?? 'id';
  const lower = entity.name.toLowerCase();
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
import { createStore } from 'solid-js/store';
import type { ${entity.name} } from '@/types';
import { seed${entity.name} } from '@/data/seed';

const STORAGE_KEY = 'implement-demo/${lower}/v1';

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function load(): ${entity.name}[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw) as ${entity.name}[];
  } catch {
    // ignore
  }
  return clone(seed${entity.name});
}

function persist(items: ${entity.name}[]) {
  try { localStorage.setItem(STORAGE_KEY, JSON.stringify(items)); } catch { /* noop */ }
}

const [state, setState] = createStore<{ items: ${entity.name}[] }>({ items: load() });

export const ${lower}Store = {
  get items() { return state.items; },
  add(item: ${entity.name}) {
    setState('items', (xs) => {
      const next = [...xs, item];
      persist(next);
      return next;
    });
  },
  update(id: string, patch: Partial<${entity.name}>) {
    const ix = state.items.findIndex((x) => String((x as Record<string, unknown>).${idName}) === id);
    if (ix === -1) return false;
    setState('items', ix, patch);
    persist(state.items);
    return true;
  },
  remove(id: string) {
    setState('items', state.items.filter((x) => String((x as Record<string, unknown>).${idName}) !== id));
    persist(state.items);
  },
  reset() {
    const fresh = clone(seed${entity.name});
    setState('items', fresh);
    persist(fresh);
  },
  get(id: string) {
    return state.items.find((x) => String((x as Record<string, unknown>).${idName}) === id);
  },
};
`;
}

export function generatePages(projectDir, spec) {
  const files = [];
  for (const page of spec.pages) {
    const code = renderPage(page, spec);
    const file = join(projectDir, 'src', 'pages', `${pageComponentName(page)}.tsx`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, code);
    files.push(file);
  }
  return files;
}

function pageComponentName(page) {
  const safe = page.name.replace(/[^a-zA-Z0-9]/g, '');
  return safe.charAt(0).toUpperCase() + safe.slice(1) + 'Page';
}

function renderPage(page, spec) {
  if (page.kind === 'list-detail') return renderListDetail(page, spec);
  if (page.kind === 'dashboard') return renderDashboard(page, spec);
  if (page.kind === 'form-wizard') return renderFormWizard(page, spec);
  return `export default function () { return <div>Unknown kind: ${page.kind}</div>; }`;
}

function renderListDetail(page, spec) {
  const entity = spec.entities.find((e) => e.name === page.primaryEntity);
  if (!entity) return `export default function () { return <div>Entity ${page.primaryEntity} not found</div>; }`;
  const lower = entity.name.toLowerCase();
  const cols = entity.fields
    .filter((f) => f.type !== 'object' && f.type !== 'array')
    .slice(0, 6)
    .map((f) => `          <th>${humanLabel(f.name)}</th>`)
    .join('\n');
  const tdFields = entity.fields
    .filter((f) => f.type !== 'object' && f.type !== 'array')
    .slice(0, 6)
    .map((f) => `              <td>{String((item as Record<string, unknown>).${f.name} ?? '—')}</td>`)
    .join('\n');
  const filters = page.filters || entity.fields.filter((f) => f.type === 'string' || f.type === 'enum').slice(0, 2).map((f) => f.name);
  const filterInputs = filters
    .map(
      (name) => `        <label class="field">
          <span>${humanLabel(name)}</span>
          <input
            value={filters.${name} ?? ''}
            onInput={(e) => setFilters('${name}', e.currentTarget.value)}
            placeholder="Buscar"
          />
        </label>`
    )
    .join('\n');
  const filterChecks = filters
    .map(
      (n) =>
        `        if (filters.${n} && !String((it as Record<string, unknown>).${n} ?? '').toLowerCase().includes((filters.${n} as string).toLowerCase())) return false;`
    )
    .join('\n');
  const actions = (page.actions || [])
    .map(
      (a) =>
        `        <button onClick={() => onAction('${a}')} disabled={!selected()}>${humanLabel(a)}</button>`
    )
    .join('\n');
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
import { createMemo, createSignal } from 'solid-js';
import { createStore } from 'solid-js/store';
import { ${lower}Store } from '@/stores/${lower}Store';
import type { ${entity.name} } from '@/types';

export default function ${pageComponentName(page)}() {
  const [filters, setFilters] = createStore<Record<string, string>>({});
  const [selected, setSelected] = createSignal<${entity.name} | null>(null);

  const rows = createMemo(() =>
    ${lower}Store.items.filter((it) => {
${filterChecks}
      return true;
    })
  );

  function onAction(action: string) {
    if (!selected()) return;
    // eslint-disable-next-line no-console
    console.info('action', action, 'on', selected());
  }

  return (
    <section class="page">
      <header><h1>${page.name}</h1></header>
      <div class="filters">
${filterInputs}
      </div>
      <div class="actions">
${actions || '        <button disabled>Sin acciones definidas</button>'}
      </div>
      <table>
        <thead><tr>
${cols}
        </tr></thead>
        <tbody>
          {rows().map((item) => (
            <tr onClick={() => setSelected(item)}>
${tdFields}
            </tr>
          ))}
        </tbody>
      </table>
      {selected() && (
        <aside class="detail">
          <header>
            <strong>Detalle</strong>
            <button onClick={() => setSelected(null)}>Cerrar</button>
          </header>
          <pre>{JSON.stringify(selected(), null, 2)}</pre>
        </aside>
      )}
    </section>
  );
}
`;
}

function renderDashboard(page, spec) {
  const entityNames = (spec.entities || []).slice(0, 3).map((e) => e.name);
  const imports = entityNames
    .map((n) => `import { ${n.toLowerCase()}Store } from '@/stores/${n.toLowerCase()}Store';`)
    .join('\n');
  const cards = entityNames
    .map(
      (n) =>
        `        <div class="kpi-card"><div class="kpi-value">{${n.toLowerCase()}Store.items.length}</div><div class="kpi-label">${humanLabel(n)}</div></div>`
    )
    .join('\n');
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
${imports}

export default function ${pageComponentName(page)}() {
  return (
    <section class="page">
      <header><h1>${page.name}</h1></header>
      <div class="kpi-grid">
${cards}
      </div>
    </section>
  );
}
`;
}

function renderFormWizard(page, spec) {
  const entity = spec.entities.find((e) => e.name === page.primaryEntity) || spec.entities[0];
  if (!entity) return `export default function () { return <div>No entity</div>; }`;
  const lower = entity.name.toLowerCase();
  const inputs = entity.fields
    .filter((f) => f.type === 'string' || f.type === 'number' || f.type === 'enum')
    .map((f) => {
      if (f.type === 'enum') {
        const opts = (f.options || []).map((o) => `          <option value="${o}">${o}</option>`).join('\n');
        return `      <label class="field">
        <span>${humanLabel(f.name)}</span>
        <select onChange={(e) => setForm('${f.name}', e.currentTarget.value)}>
${opts}
        </select>
      </label>`;
      }
      const inputType = f.type === 'number' ? 'number' : 'text';
      const cast = inputType === 'number' ? 'Number(e.currentTarget.value)' : 'e.currentTarget.value';
      return `      <label class="field">
        <span>${humanLabel(f.name)}</span>
        <input type="${inputType}" onInput={(e) => setForm('${f.name}', ${cast})} />
      </label>`;
    })
    .join('\n');
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
import { createStore } from 'solid-js/store';
import { ${lower}Store } from '@/stores/${lower}Store';
import type { ${entity.name} } from '@/types';

export default function ${pageComponentName(page)}() {
  const [form, setForm] = createStore<Partial<${entity.name}>>({});

  function submit(e: SubmitEvent) {
    e.preventDefault();
    ${lower}Store.add(form as ${entity.name});
  }

  return (
    <section class="page">
      <header><h1>${page.name}</h1></header>
      <form onSubmit={submit}>
${inputs}
        <button type="submit">Crear</button>
      </form>
    </section>
  );
}
`;
}

function humanLabel(name) {
  return String(name).replace(/[-_]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export function generateRouter(projectDir, spec) {
  const imports = spec.pages.map((p) => {
    const name = pageComponentName(p);
    return `import ${name} from './pages/${name}';`;
  });
  const routes = spec.pages
    .map((p) => {
      const name = pageComponentName(p);
      return `      <Route path="${p.path}" component={${name}} />`;
    })
    .join('\n');
  const firstPath = spec.pages[0]?.path ?? '/';
  const code = `// Auto-generated by bonita-page implement-demo. Edit freely.
import { HashRouter, Route, Navigate } from '@solidjs/router';
${imports.join('\n')}

export default function App() {
  return (
    <HashRouter>
      <Route path="/" component={() => <Navigate href="${firstPath}" />} />
${routes}
    </HashRouter>
  );
}
`;
  const file = join(projectDir, 'src', 'App.tsx');
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, code);
  return [file];
}
