// Svelte 5 framework adapter for `implement_demo_for_framework`.
// Uses Svelte 5 runes ($state, $derived) in .svelte.ts stores and
// svelte-spa-router for hash routing.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

export const FRAMEWORK = 'svelte';

export function generateStores(projectDir, spec) {
  const files = [];
  for (const entity of spec.entities) {
    const file = join(projectDir, 'src', 'stores', `${entity.name.toLowerCase()}.svelte.ts`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, svelteStore(entity));
    files.push(file);
  }
  return files;
}

function svelteStore(entity) {
  const idField = entity.fields.find((f) => f.name.toLowerCase() === 'id') || entity.fields[0];
  const idName = idField?.name ?? 'id';
  const lower = entity.name.toLowerCase();
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
// Runes (\$state, \$derived) require a .svelte.ts extension.
import type { ${entity.name} } from '../types';
import { seed${entity.name} } from '../data/seed';

const STORAGE_KEY = 'implement-demo/${lower}/v1';

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function load(): ${entity.name}[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw) as ${entity.name}[];
  } catch {
    // ignore
  }
  return clone(seed${entity.name});
}

function persist(items: ${entity.name}[]) {
  try { localStorage.setItem(STORAGE_KEY, JSON.stringify(items)); } catch { /* noop */ }
}

class ${entity.name}Store {
  items = \$state<${entity.name}[]>(load());

  add(item: ${entity.name}) {
    this.items = [...this.items, item];
    persist(this.items);
  }

  update(id: string, patch: Partial<${entity.name}>) {
    const ix = this.items.findIndex((x) => String((x as Record<string, unknown>).${idName}) === id);
    if (ix === -1) return false;
    const next = [...this.items];
    next[ix] = { ...next[ix], ...patch };
    this.items = next;
    persist(this.items);
    return true;
  }

  remove(id: string) {
    this.items = this.items.filter((x) => String((x as Record<string, unknown>).${idName}) !== id);
    persist(this.items);
  }

  reset() {
    this.items = clone(seed${entity.name});
    persist(this.items);
  }

  get(id: string) {
    return this.items.find((x) => String((x as Record<string, unknown>).${idName}) === id);
  }
}

export const ${lower}Store = new ${entity.name}Store();
`;
}

export function generatePages(projectDir, spec) {
  const files = [];
  for (const page of spec.pages) {
    const code = renderPage(page, spec);
    const file = join(projectDir, 'src', 'pages', `${pageComponentName(page)}.svelte`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, code);
    files.push(file);
  }
  return files;
}

function pageComponentName(page) {
  const safe = page.name.replace(/[^a-zA-Z0-9]/g, '');
  return safe.charAt(0).toUpperCase() + safe.slice(1) + 'Page';
}

function renderPage(page, spec) {
  if (page.kind === 'list-detail') return renderListDetail(page, spec);
  if (page.kind === 'dashboard') return renderDashboard(page, spec);
  if (page.kind === 'form-wizard') return renderFormWizard(page, spec);
  return `<p>Unknown page kind: ${page.kind}</p>`;
}

function renderListDetail(page, spec) {
  const entity = spec.entities.find((e) => e.name === page.primaryEntity);
  if (!entity) return `<p>Entity ${page.primaryEntity} not found</p>`;
  const lower = entity.name.toLowerCase();
  const cols = entity.fields
    .filter((f) => f.type !== 'object' && f.type !== 'array')
    .slice(0, 6)
    .map((f) => `        <th>${humanLabel(f.name)}</th>`)
    .join('\n');
  const tdFields = entity.fields
    .filter((f) => f.type !== 'object' && f.type !== 'array')
    .slice(0, 6)
    .map((f) => `          <td>{String(item.${f.name} ?? '—')}</td>`)
    .join('\n');
  const filters = (page.filters || entity.fields.filter((f) => f.type === 'string' || f.type === 'enum').slice(0, 2).map((f) => f.name));
  const filterInputs = filters
    .map(
      (name) => `      <label class="field">
        <span>${humanLabel(name)}</span>
        <input bind:value={filters.${name}} placeholder="Buscar" />
      </label>`
    )
    .join('\n');
  const filterDecls = filters.map((n) => `    ${n}: '',`).join('\n');
  const filterChecks = filters
    .map(
      (n) =>
        `      if (filters.${n} && !String((it as Record<string, unknown>).${n} ?? '').toLowerCase().includes(filters.${n}.toLowerCase())) return false;`
    )
    .join('\n');
  const actions = (page.actions || []).map(
    (a) => `      <button on:click={() => onAction('${a}')} disabled={!selected}>${humanLabel(a)}</button>`
  ).join('\n');
  return `<!-- Auto-generated by bonita-page implement-demo. Edit freely. -->
<script lang="ts">
  import { ${lower}Store } from '../stores/${lower}.svelte';
  import type { ${entity.name} } from '../types';

  let filters = \$state<Record<string, string>>({
${filterDecls}
  });
  let selected = \$state<${entity.name} | null>(null);

  const rows = \$derived(${lower}Store.items.filter((it) => {
${filterChecks}
    return true;
  }));

  function onAction(action: string) {
    if (!selected) return;
    console.info('action', action, 'on', selected);
  }
</script>

<section class="page">
  <header><h1>${page.name}</h1></header>
  <div class="filters">
${filterInputs}
  </div>
  <div class="actions">
${actions || '    <button disabled>Sin acciones definidas</button>'}
  </div>
  <table>
    <thead><tr>
${cols}
    </tr></thead>
    <tbody>
      {#each rows as item}
        <tr on:click={() => (selected = item)}>
${tdFields}
        </tr>
      {/each}
    </tbody>
  </table>
  {#if selected}
    <aside class="detail">
      <header>
        <strong>Detalle</strong>
        <button on:click={() => (selected = null)}>Cerrar</button>
      </header>
      <pre>{JSON.stringify(selected, null, 2)}</pre>
    </aside>
  {/if}
</section>
`;
}

function renderDashboard(page, spec) {
  const entityNames = (spec.entities || []).slice(0, 3).map((e) => e.name);
  const imports = entityNames
    .map((n) => `  import { ${n.toLowerCase()}Store } from '../stores/${n.toLowerCase()}.svelte';`)
    .join('\n');
  const cards = entityNames
    .map(
      (n) =>
        `    <div class="kpi-card"><div class="kpi-value">{${n.toLowerCase()}Store.items.length}</div><div class="kpi-label">${humanLabel(n)}</div></div>`
    )
    .join('\n');
  return `<!-- Auto-generated by bonita-page implement-demo. Edit freely. -->
<script lang="ts">
${imports}
</script>

<section class="page">
  <header><h1>${page.name}</h1></header>
  <div class="kpi-grid">
${cards}
  </div>
</section>
`;
}

function renderFormWizard(page, spec) {
  const entity = spec.entities.find((e) => e.name === page.primaryEntity) || spec.entities[0];
  if (!entity) return `<p>No entity</p>`;
  const lower = entity.name.toLowerCase();
  const fieldInits = entity.fields
    .filter((f) => f.type === 'string' || f.type === 'number' || f.type === 'enum')
    .map((f) => `    ${f.name}: ${f.type === 'number' ? '0' : "''"},`)
    .join('\n');
  const inputs = entity.fields
    .filter((f) => f.type === 'string' || f.type === 'number' || f.type === 'enum')
    .map((f) => {
      if (f.type === 'enum') {
        const opts = (f.options || []).map((o) => `      <option value="${o}">${o}</option>`).join('\n');
        return `    <label class="field">
      <span>${humanLabel(f.name)}</span>
      <select bind:value={form.${f.name}}>
${opts}
      </select>
    </label>`;
      }
      const inputType = f.type === 'number' ? 'number' : 'text';
      return `    <label class="field">
      <span>${humanLabel(f.name)}</span>
      <input type="${inputType}" bind:value={form.${f.name}} />
    </label>`;
    })
    .join('\n');
  return `<!-- Auto-generated by bonita-page implement-demo. Edit freely. -->
<script lang="ts">
  import { ${lower}Store } from '../stores/${lower}.svelte';
  import type { ${entity.name} } from '../types';

  let form = \$state<Partial<${entity.name}>>({
${fieldInits}
  });

  function submit(e: SubmitEvent) {
    e.preventDefault();
    ${lower}Store.add(form as ${entity.name});
    form = {${entity.fields
      .filter((f) => f.type === 'string' || f.type === 'number' || f.type === 'enum')
      .map((f) => ` ${f.name}: ${f.type === 'number' ? '0' : "''"}`)
      .join(',')} };
  }
</script>

<section class="page">
  <header><h1>${page.name}</h1></header>
  <form on:submit={submit}>
${inputs}
    <button type="submit">Crear</button>
  </form>
</section>
`;
}

function humanLabel(name) {
  return String(name).replace(/[-_]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export function generateRouter(projectDir, spec) {
  const routes = spec.pages.map((p) => {
    const name = pageComponentName(p);
    return `  '${p.path}': () => import('./pages/${name}.svelte'),`;
  });
  const firstPath = spec.pages[0]?.path ?? '/';
  const code = `// Auto-generated by bonita-page implement-demo. Edit freely.
// svelte-spa-router uses a route map: { '/path': Component | () => Promise<Component> }.
import { replace } from 'svelte-spa-router';

export const routes = {
${routes.join('\n')}
  '*': () => { replace('${firstPath}'); return null; },
};
`;
  const file = join(projectDir, 'src', 'routes.ts');
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, code);
  return [file];
}
