// Vue framework adapter for `implement_demo_for_framework`.
//
// What it owns:
//   - Pinia store per entity (CRUD + filtering, hydrates from seed)
//   - One page per spec.pages[]
//   - Optional palette injection into tokens.css
//   - Route table generation
//
// Stays in sync with the project scaffolded by `bonita-page scaffold --framework=vue`.

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

export const FRAMEWORK = 'vue';

export function generateStores(projectDir, spec) {
  const files = [];
  for (const entity of spec.entities) {
    const store = vuePiniaStore(entity);
    const file = join(projectDir, 'src', 'stores', `${entity.name.toLowerCase()}.ts`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, store);
    files.push(file);
  }
  return files;
}

function vuePiniaStore(entity) {
  const idField = entity.fields.find((f) => f.name.toLowerCase() === 'id') || entity.fields[0];
  const idType = idField?.type === 'enum' ? 'string' : 'string';
  const lowerName = entity.name.toLowerCase();
  return `// Auto-generated by bonita-page implement-demo. Edit freely.
import { defineStore } from 'pinia';
import { computed, ref } from 'vue';
import type { ${entity.name} } from '@/types';
import { seed${entity.name} } from '@/data/seed';

const STORAGE_KEY = 'implement-demo/${lowerName}/v1';

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function load(): ${entity.name}[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw) as ${entity.name}[];
  } catch {
    // ignore corruption — fall through to seed
  }
  return clone(seed${entity.name});
}

export const use${entity.name}Store = defineStore('${lowerName}', () => {
  const items = ref<${entity.name}[]>(load());

  function persist() {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(items.value));
    } catch {
      // localStorage disabled or full — silent for the demo
    }
  }

  const byId = computed(() => {
    const map = new Map<${idType}, ${entity.name}>();
    for (const it of items.value) map.set(it.${idField?.name ?? 'id'} as ${idType}, it);
    return map;
  });

  function get(id: ${idType}): ${entity.name} | undefined {
    return byId.value.get(id);
  }

  function add(item: ${entity.name}) {
    items.value.push(item);
    persist();
  }

  function update(id: ${idType}, patch: Partial<${entity.name}>) {
    const ix = items.value.findIndex((x) => (x.${idField?.name ?? 'id'} as ${idType}) === id);
    if (ix === -1) return false;
    items.value[ix] = { ...items.value[ix], ...patch };
    persist();
    return true;
  }

  function remove(id: ${idType}) {
    items.value = items.value.filter((x) => (x.${idField?.name ?? 'id'} as ${idType}) !== id);
    persist();
  }

  function reset() {
    items.value = clone(seed${entity.name});
    persist();
  }

  return { items, byId, get, add, update, remove, reset };
});
`;
}

export function generatePages(projectDir, spec) {
  const files = [];
  for (const page of spec.pages) {
    const code = renderPage(page, spec);
    const file = join(projectDir, 'src', 'pages', `${pageComponentName(page)}.vue`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, code);
    files.push(file);
  }
  return files;
}

function pageComponentName(page) {
  const safe = page.name.replace(/[^a-zA-Z0-9]/g, '');
  return safe.charAt(0).toUpperCase() + safe.slice(1) + 'Page';
}

function renderPage(page, spec) {
  if (page.kind === 'list-detail') return renderListDetail(page, spec);
  if (page.kind === 'dashboard') return renderDashboard(page, spec);
  if (page.kind === 'form-wizard') return renderFormWizard(page, spec);
  return `<template><div>Unknown page kind: ${page.kind}</div></template>`;
}

function renderListDetail(page, spec) {
  const entity = spec.entities.find((e) => e.name === page.primaryEntity);
  if (!entity) {
    return `<template><div>Entity ${page.primaryEntity} not found in spec.</div></template>`;
  }
  const columns = entity.fields
    .filter((f) => f.type !== 'object' && f.type !== 'array')
    .slice(0, 6)
    .map((f) => `    <el-table-column prop="${f.name}" label="${humanLabel(f.name)}" min-width="120" />`)
    .join('\n');
  const actions = (page.actions || []).map((a) => `      <el-button @click="onAction('${a}')">${humanLabel(a)}</el-button>`).join('\n');
  const filterFields = (page.filters || entity.fields.filter((f) => f.type === 'string' || f.type === 'enum').slice(0, 2).map((f) => f.name));
  const filterControls = filterFields
    .map((name) => {
      const field = entity.fields.find((f) => f.name === name);
      if (!field) return '';
      if (field.type === 'enum') {
        const opts = (field.options || []).map((o) => `        <el-option label="${o}" value="${o}" />`).join('\n');
        return `      <div class="field">
        <span class="field-label">${humanLabel(name)}</span>
        <el-select v-model="filters.${name}" aria-label="${humanLabel(name)}" placeholder="Todos" clearable style="width: 100%">
${opts}
        </el-select>
      </div>`;
      }
      return `      <div class="field">
        <span class="field-label">${humanLabel(name)}</span>
        <el-input v-model="filters.${name}" aria-label="${humanLabel(name)}" placeholder="Buscar" clearable />
      </div>`;
    })
    .join('\n');

  return `<script setup lang="ts">
import { computed, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { use${entity.name}Store } from '@/stores/${entity.name.toLowerCase()}';
import type { ${entity.name} } from '@/types';

const store = use${entity.name}Store();
const selected = ref<${entity.name} | null>(null);

const filters = ref<Record<string, string>>({
${filterFields.map((n) => `  ${n}: '',`).join('\n')}
});

const rows = computed(() =>
  store.items.filter((it) => {
${filterFields
  .map(
    (n) => `    if (filters.value.${n} && !String((it as Record<string, unknown>).${n} ?? '').toLowerCase().includes(filters.value.${n}.toLowerCase())) return false;`
  )
  .join('\n')}
    return true;
  })
);

function select(row: ${entity.name}) {
  selected.value = row;
}

function onAction(action: string) {
  if (!selected.value) {
    ElMessage.warning('Seleccioná un registro primero');
    return;
  }
  ElMessage.success(\`Acción "\${action}" aplicada a \${(selected.value as Record<string, unknown>).id ?? 'registro'}\`);
}
</script>

<template>
  <section class="page">
    <header class="page-header">
      <h1>${page.name}</h1>
    </header>

    <div class="filters">
${filterControls}
    </div>

    <div v-if="page.actions?.length || true" class="actions-bar">
${actions || '      <el-button disabled>Sin acciones definidas</el-button>'}
    </div>

    <el-table
      :data="rows"
      height="100%"
      stripe
      highlight-current-row
      @row-click="select"
    >
${columns}
    </el-table>

    <aside v-if="selected" class="detail">
      <header>
        <strong>Detalle</strong>
        <el-button @click="selected = null" text>Cerrar</el-button>
      </header>
      <pre>{{ JSON.stringify(selected, null, 2) }}</pre>
    </aside>
  </section>
</template>

<style scoped>
.page { display: flex; flex-direction: column; gap: 1rem; height: 100%; }
.page-header h1 { margin: 0; font-size: 1.3rem; font-weight: 700; }
.filters { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: .75rem; background: #fff; border: 1px solid var(--border, #dde3ef); border-radius: .5rem; padding: 1rem; }
.field-label { display: block; font-size: .68rem; font-weight: 600; text-transform: uppercase; letter-spacing: .04em; color: var(--muted, #6b7a99); margin-bottom: .3rem; }
.actions-bar { display: flex; gap: .5rem; flex-wrap: wrap; background: #fff; border: 1px solid var(--border, #dde3ef); border-radius: .5rem; padding: .75rem 1rem; }
.detail { background: #fff; border: 1px solid var(--border, #dde3ef); border-radius: .5rem; padding: 1rem; }
.detail header { display: flex; justify-content: space-between; align-items: center; margin-bottom: .5rem; }
.detail pre { background: #f8fafc; padding: .75rem; border-radius: .35rem; font-size: .8rem; overflow-x: auto; }
</style>
`;
}

function renderDashboard(page, spec) {
  const entityNames = (spec.entities || []).slice(0, 3).map((e) => e.name);
  const cards = entityNames
    .map(
      (n) =>
        `      <div class="kpi-card"><div class="kpi-value">{{ store${n}.items.length }}</div><div class="kpi-label">${humanLabel(n)}</div></div>`
    )
    .join('\n');
  const imports = entityNames
    .map((n) => `import { use${n}Store } from '@/stores/${n.toLowerCase()}';`)
    .join('\n');
  const stores = entityNames
    .map((n) => `const store${n} = use${n}Store();`)
    .join('\n');
  return `<script setup lang="ts">
${imports}

${stores}
</script>

<template>
  <section class="page">
    <header class="page-header">
      <h1>${page.name}</h1>
    </header>
    <div class="kpi-grid">
${cards}
    </div>
  </section>
</template>

<style scoped>
.page { display: flex; flex-direction: column; gap: 1rem; }
.page-header h1 { margin: 0; font-size: 1.3rem; font-weight: 700; }
.kpi-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; }
.kpi-card { background: #fff; border: 1px solid var(--border, #dde3ef); border-radius: .5rem; padding: 1rem 1.2rem; }
.kpi-value { font-size: 1.5rem; font-weight: 700; }
.kpi-label { font-size: .72rem; color: var(--muted, #6b7a99); margin-top: .15rem; }
</style>
`;
}

function renderFormWizard(page, spec) {
  const entity = spec.entities.find((e) => e.name === page.primaryEntity) || spec.entities[0];
  if (!entity) return `<template><div>No entity available for form-wizard</div></template>`;
  const inputs = entity.fields
    .filter((f) => f.type === 'string' || f.type === 'number' || f.type === 'enum')
    .map((f) => {
      if (f.type === 'enum') {
        const opts = (f.options || []).map((o) => `        <el-option label="${o}" value="${o}" />`).join('\n');
        return `    <el-form-item label="${humanLabel(f.name)}">
      <el-select v-model="form.${f.name}" aria-label="${humanLabel(f.name)}" style="width: 100%">
${opts}
      </el-select>
    </el-form-item>`;
      }
      const type = f.type === 'number' ? 'number' : 'text';
      return `    <el-form-item label="${humanLabel(f.name)}">
      <el-input v-model="form.${f.name}" aria-label="${humanLabel(f.name)}" type="${type}" />
    </el-form-item>`;
    })
    .join('\n');
  return `<script setup lang="ts">
import { reactive } from 'vue';
import { ElMessage } from 'element-plus';
import { use${entity.name}Store } from '@/stores/${entity.name.toLowerCase()}';
import type { ${entity.name} } from '@/types';

const store = use${entity.name}Store();
const form = reactive<Partial<${entity.name}>>({});

function submit() {
  store.add(form as ${entity.name});
  ElMessage.success('Registro creado');
}
</script>

<template>
  <section class="page">
    <header class="page-header">
      <h1>${page.name}</h1>
    </header>
    <el-form label-position="top" @submit.prevent="submit">
${inputs}
      <el-form-item>
        <el-button type="primary" native-type="submit">Crear</el-button>
      </el-form-item>
    </el-form>
  </section>
</template>

<style scoped>
.page { display: flex; flex-direction: column; gap: 1rem; max-width: 640px; }
.page-header h1 { margin: 0; font-size: 1.3rem; font-weight: 700; }
</style>
`;
}

function humanLabel(name) {
  return String(name).replace(/[-_]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export function generateRouter(projectDir, spec) {
  const routerFile = join(projectDir, 'src', 'router', 'index.ts');
  const imports = [];
  const routes = [];
  for (const page of spec.pages) {
    const name = pageComponentName(page);
    imports.push(`const ${name} = () => import('@/pages/${name}.vue');`);
    routes.push(`    { path: '${page.path.replace(/^\//, '')}', name: '${page.name}', component: ${name} },`);
  }
  const firstPath = spec.pages[0]?.path?.replace(/^\//, '') ?? '';
  const code = `import { createRouter, createWebHashHistory, type RouteRecordRaw } from 'vue-router';

${imports.join('\n')}

const routes: RouteRecordRaw[] = [
  {
    path: '/',
    component: () => import('@/App.vue'),
    children: [
      { path: '', redirect: '${firstPath}' },
${routes.join('\n')}
    ],
  },
  { path: '/:pathMatch(.*)*', redirect: '/' },
];

export default createRouter({ history: createWebHashHistory(), routes });
`;
  mkdirSync(dirname(routerFile), { recursive: true });
  writeFileSync(routerFile, code);
  return [routerFile];
}
