// Generate framework-agnostic TypeScript domain layer for the demo:
//   - src/types/<entity>.ts         (interface per entity)
//   - src/data/seed.ts              (mock seed arrays, deterministic)
//
// Framework-specific store generation lives in framework adapters
// (see scripts/implement-demo/frameworks/<framework>.js).

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { generateSeed } from './seed-values.js';

const TYPE_MAP = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  date: 'string', // ISO or dd/MM/yyyy — kept as string for portability
  enum: null,     // produced inline as literal union below
  object: 'Record<string, unknown>',
  array: 'unknown[]',
};

function fieldToTsType(field, entityNamesByName) {
  if (field.type === 'enum') {
    const opts = (field.options || []).map((o) => `'${o.replace(/'/g, "\\'")}'`).join(' | ');
    return opts || 'string';
  }
  if (field.ref && entityNamesByName.has(field.ref)) {
    // Foreign-key reference — we represent it as the referenced entity's id type (string)
    return 'string';
  }
  return TYPE_MAP[field.type] || 'unknown';
}

export function generateDomain(projectDir, spec) {
  const entityNamesByName = new Set(spec.entities.map((e) => e.name));
  const filesWritten = [];

  // 1. One types file per entity
  for (const entity of spec.entities) {
    const lines = [];
    lines.push(`// Auto-generated by bonita-page implement-demo. Edit freely.`);
    lines.push(`export interface ${entity.name} {`);
    for (const f of entity.fields) {
      const tsType = fieldToTsType(f, entityNamesByName);
      lines.push(`  ${f.name}: ${tsType};`);
    }
    lines.push(`}`);
    const file = join(projectDir, 'src', 'types', `${entity.name}.ts`);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, lines.join('\n') + '\n');
    filesWritten.push(file);
  }

  // 2. Aggregated index file for easy imports
  const index = spec.entities
    .map((e) => `export type { ${e.name} } from './${e.name}';`)
    .join('\n');
  const indexFile = join(projectDir, 'src', 'types', 'index.ts');
  writeFileSync(indexFile, index + '\n');
  filesWritten.push(indexFile);

  // 3. Seed data — one big file with one export per entity
  const seedLines = [];
  seedLines.push(`// Auto-generated by bonita-page implement-demo.`);
  seedLines.push(`// Deterministic seeds — re-running implement-demo with the same spec produces the same data.`);
  seedLines.push(`import type { ${spec.entities.map((e) => e.name).join(', ')} } from '@/types';`);
  seedLines.push('');
  for (const entity of spec.entities) {
    const seed = generateSeed(entity);
    seedLines.push(`export const seed${entity.name}: ${entity.name}[] = ${JSON.stringify(seed, null, 2)};`);
    seedLines.push('');
  }
  const seedFile = join(projectDir, 'src', 'data', 'seed.ts');
  mkdirSync(dirname(seedFile), { recursive: true });
  writeFileSync(seedFile, seedLines.join('\n'));
  filesWritten.push(seedFile);

  return filesWritten;
}
